server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hotel_microservice
    username: postgres
    password: Rohit@123

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true